"""Initial migration - create all tables

Revision ID: 8d89d93cd099
Revises: 
Create Date: 2025-09-04 22:35:38.700046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d89d93cd099'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passenger_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passenger_types_id'), 'passenger_types', ['id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('journeys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journeys_id'), 'journeys', ['id'], unique=False)
    op.create_table('train_companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_companies_id'), 'train_companies', ['id'], unique=False)
    op.create_table('user_has_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_has_roles_id'), 'user_has_roles', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_unique_string', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('journey_id', sa.BigInteger(), nullable=True),
    sa.Column('passenger_type_id', sa.BigInteger(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qr_code_data', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('issued_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ),
    sa.ForeignKeyConstraint(['passenger_type_id'], ['passenger_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_unique_string')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.create_index(op.f('ix_tickets_valid_from'), 'tickets', ['valid_from'], unique=False)
    op.create_index(op.f('ix_tickets_valid_until'), 'tickets', ['valid_until'], unique=False)
    op.create_table('train_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['train_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_lines_id'), 'train_lines', ['id'], unique=False)
    op.create_table('distance_zones',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('line_id', sa.BigInteger(), nullable=False),
    sa.Column('zone_number', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('per_station_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['train_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distance_zones_id'), 'distance_zones', ['id'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('line_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('long', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('zone_number', sa.Integer(), nullable=True),
    sa.Column('is_interchange', sa.Boolean(), nullable=True),
    sa.Column('platform_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['train_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_index(op.f('ix_stations_is_interchange'), 'stations', ['is_interchange'], unique=False)
    op.create_index(op.f('ix_stations_name'), 'stations', ['name'], unique=False)
    op.create_table('train_services',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('line_id', sa.BigInteger(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['train_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_services_id'), 'train_services', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('from_station', sa.BigInteger(), nullable=False),
    sa.Column('to_station', sa.BigInteger(), nullable=False),
    sa.Column('transport_type', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_travel_time_minutes', sa.Integer(), nullable=True),
    sa.Column('service_frequency_minutes', sa.Integer(), nullable=True),
    sa.Column('base_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_station'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['to_station'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_from_station'), 'routes', ['from_station'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_to_station'), 'routes', ['to_station'], unique=False)
    op.create_table('service_status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('line_id', sa.BigInteger(), nullable=True),
    sa.Column('station_id', sa.BigInteger(), nullable=True),
    sa.Column('status_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['train_lines.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_status_id'), 'service_status', ['id'], unique=False)
    op.create_index(op.f('ix_service_status_is_active'), 'service_status', ['is_active'], unique=False)
    op.create_index(op.f('ix_service_status_line_id'), 'service_status', ['line_id'], unique=False)
    op.create_index(op.f('ix_service_status_station_id'), 'service_status', ['station_id'], unique=False)
    op.create_table('station_facilities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('station_id', sa.BigInteger(), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('location_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_facilities_id'), 'station_facilities', ['id'], unique=False)
    op.create_table('transfer_points',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('station_a_id', sa.BigInteger(), nullable=False),
    sa.Column('station_b_id', sa.BigInteger(), nullable=False),
    sa.Column('walking_time_minutes', sa.Integer(), nullable=True),
    sa.Column('walking_distance_meters', sa.Integer(), nullable=True),
    sa.Column('transfer_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['station_a_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['station_b_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_points_id'), 'transfer_points', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_points_is_active'), 'transfer_points', ['is_active'], unique=False)
    op.create_index(op.f('ix_transfer_points_station_a_id'), 'transfer_points', ['station_a_id'], unique=False)
    op.create_index(op.f('ix_transfer_points_station_b_id'), 'transfer_points', ['station_b_id'], unique=False)
    op.create_table('fare_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('passenger_type_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['passenger_type_id'], ['passenger_types.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fare_rules_id'), 'fare_rules', ['id'], unique=False)
    op.create_table('journey_segments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('journey_id', sa.BigInteger(), nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_segments_id'), 'journey_segments', ['id'], unique=False)
    op.create_table('ticket_routes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('depart_station_id', sa.BigInteger(), nullable=False),
    sa.Column('arrive_station_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['arrive_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['depart_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_routes_id'), 'ticket_routes', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_routes_ticket_id'), 'ticket_routes', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_routes_ticket_id'), table_name='ticket_routes')
    op.drop_index(op.f('ix_ticket_routes_id'), table_name='ticket_routes')
    op.drop_table('ticket_routes')
    op.drop_index(op.f('ix_journey_segments_id'), table_name='journey_segments')
    op.drop_table('journey_segments')
    op.drop_index(op.f('ix_fare_rules_id'), table_name='fare_rules')
    op.drop_table('fare_rules')
    op.drop_index(op.f('ix_transfer_points_station_b_id'), table_name='transfer_points')
    op.drop_index(op.f('ix_transfer_points_station_a_id'), table_name='transfer_points')
    op.drop_index(op.f('ix_transfer_points_is_active'), table_name='transfer_points')
    op.drop_index(op.f('ix_transfer_points_id'), table_name='transfer_points')
    op.drop_table('transfer_points')
    op.drop_index(op.f('ix_station_facilities_id'), table_name='station_facilities')
    op.drop_table('station_facilities')
    op.drop_index(op.f('ix_service_status_station_id'), table_name='service_status')
    op.drop_index(op.f('ix_service_status_line_id'), table_name='service_status')
    op.drop_index(op.f('ix_service_status_is_active'), table_name='service_status')
    op.drop_index(op.f('ix_service_status_id'), table_name='service_status')
    op.drop_table('service_status')
    op.drop_index(op.f('ix_routes_to_station'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_from_station'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_train_services_id'), table_name='train_services')
    op.drop_table('train_services')
    op.drop_index(op.f('ix_stations_name'), table_name='stations')
    op.drop_index(op.f('ix_stations_is_interchange'), table_name='stations')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_distance_zones_id'), table_name='distance_zones')
    op.drop_table('distance_zones')
    op.drop_index(op.f('ix_train_lines_id'), table_name='train_lines')
    op.drop_table('train_lines')
    op.drop_index(op.f('ix_tickets_valid_until'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_valid_from'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_user_has_roles_id'), table_name='user_has_roles')
    op.drop_table('user_has_roles')
    op.drop_index(op.f('ix_train_companies_id'), table_name='train_companies')
    op.drop_table('train_companies')
    op.drop_index(op.f('ix_journeys_id'), table_name='journeys')
    op.drop_table('journeys')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_passenger_types_id'), table_name='passenger_types')
    op.drop_table('passenger_types')
    # ### end Alembic commands ###
